### ISSUE TITLE
Great Work! Few queries... 

### ISSUE THREAD

**Issue by VIROBO-15** [gwang-kim/DiffusionCLIP#13]
Can you Please provide the code for the obtaining the Quantitative results reported in the Table 1 and Table 3 of the paper?

**Comment by gwang-kim** [comment]
You can calculate the metrics following the information in the Supplementary material in our paper.

Here are several repositories for the evaluation.

- Image quality assessment: https://github.com/chaofengc/IQA-PyTorch.git
- face identity network: https://github.com/CoinCheung/BiSeNet
- semantic segmentation network: https://github.com/CSAILVision/semantic-segmentation-pytorch
