### ISSUE TITLE
What is LMDB_train? 

### ISSUE THREAD

**Issue by songyiren98** [gwang-kim/DiffusionCLIP#14]
lmdb.Error: data/celeba_hq/LMDB_train: No such file or directory
I want to train a new effect on CelebA_HQ_dataset, thank you.

**Comment by gwang-kim** [comment]
As you can find in the Dataset section in `README.md`, 

You need to use the below commands to download CelebA-HQ dataset.
```
# CelebA-HQ 256x256
bash data_download.sh celeba_hq .
```
Then, you can find the data like the below structure in `DiffusionCLIP/data`.
```
data
└── celeba_hq
    ├── LMDB_test
    │   ├── data.mdb
    │   └── lock.mdb
    ├── LMDB_train
    │   ├── data.mdb
    │   └── lock.mdb
    └── LMDB_val
        ├── data.mdb
        └── lock.mdb
    └── raw_images
        ├── train
                 :
```

**Comment by ZHOU1023** [comment]
How long does the data preparation process take? Now I can only see the "LMDB_train" without "LMDB_val" and "LMDB_test".
