### ISSUE TITLE
Request the code to  train the Diffusion Model

### ISSUE THREAD

**Issue by ZERO2ER0** [gwang-kim/DiffusionCLIP#18]
Hi, you work is amazing and  inspiring. I am  following your great work and trying to train the diffusion model in another dataset. Could you help with training code? Thank you very much.

**Comment by gwang-kim** [comment]
Thanks for your interest in our research!
My code is based on SDEdit repo(https://github.com/ermongroup/SDEdit) which is based on DDIM repo (https://github.com/ermongroup/ddim).
You can find the code of training diffusion models in DDIM repo.

**Comment by ZERO2ER0** [comment]
Thank you very much! I wish you every success in your research
