### ISSUE TITLE
tanned model error

### ISSUE THREAD

**Issue by loboere** [gwang-kim/DiffusionCLIP#2]
Downloading checkpoint/human_tanned_t201.pth ...
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/pydrive/files.py](https://localhost:8080/#) in FetchMetadata(self, fields, fetch_all)
    236                                                  fields=fields)\
--> 237           .execute(http=self.http)
    238       except errors.HttpError as error:

5 frames
HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/15Twto21spGLwiby7_yGO_xquFXtfJIAo?fields=alternateLink%2CappDataContents%2CcanComment%2CcanReadRevisions%2Ccopyable%2CcreatedDate%2CdefaultOpenWithLink%2Cdescription%2CdownloadUrl%2Ceditable%2CembedLink%2Cetag%2CexplicitlyTrashed%2CexportLinks%2CfileExtension%2CfileSize%2CfolderColorRgb%2CfullFileExtension%2CheadRevisionId%2CiconLink%2Cid%2CimageMediaMetadata%2CindexableText%2CisAppAuthorized%2Ckind%2Clabels%2ClastModifyingUser%2ClastModifyingUserName%2ClastViewedByMeDate%2CmarkedViewedByMeDate%2Cmd5Checksum%2CmimeType%2CmodifiedByMeDate%2CmodifiedDate%2CopenWithLinks%2CoriginalFilename%2CownedByMe%2CownerNames%2Cowners%2Cparents%2Cpermissions%2Cproperties%2CquotaBytesUsed%2CselfLink%2Cshareable%2Cshared%2CsharedWithMeDate%2CsharingUser%2Cspaces%2Cthumbnail%2CthumbnailLink%2Ctitle%2CuserPermission%2Cversion%2CvideoMediaMetadata%2CwebContentLink%2CwebViewLink%2CwritersCanShare&alt=json returned "File not found: 15Twto21spGLwiby7_yGO_xquFXtfJIAo". Details: "File not found: 15Twto21spGLwiby7_yGO_xquFXtfJIAo">

During handling of the above exception, another exception occurred:

ApiRequestError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/pydrive/files.py](https://localhost:8080/#) in FetchMetadata(self, fields, fetch_all)
    237           .execute(http=self.http)
    238       except errors.HttpError as error:
--> 239         raise ApiRequestError(error)
    240       else:
    241         self.uploaded = True

ApiRequestError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/15Twto21spGLwiby7_yGO_xquFXtfJIAo?fields=alternateLink%2CappDataContents%2CcanComment%2CcanReadRevisions%2Ccopyable%2CcreatedDate%2CdefaultOpenWithLink%2Cdescription%2CdownloadUrl%2Ceditable%2CembedLink%2Cetag%2CexplicitlyTrashed%2CexportLinks%2CfileExtension%2CfileSize%2CfolderColorRgb%2CfullFileExtension%2CheadRevisionId%2CiconLink%2Cid%2CimageMediaMetadata%2CindexableText%2CisAppAuthorized%2Ckind%2Clabels%2ClastModifyingUser%2ClastModifyingUserName%2ClastViewedByMeDate%2CmarkedViewedByMeDate%2Cmd5Checksum%2CmimeType%2CmodifiedByMeDate%2CmodifiedDate%2CopenWithLinks%2CoriginalFilename%2CownedByMe%2CownerNames%2Cowners%2Cparents%2Cpermissions%2Cproperties%2CquotaBytesUsed%2CselfLink%2Cshareable%2Cshared%2CsharedWithMeDate%2CsharingUser%2Cspaces%2Cthumbnail%2CthumbnailLink%2Ctitle%2CuserPermission%2Cversion%2CvideoMediaMetadata%2CwebContentLink%2CwebViewLink%2CwritersCanShare&alt=json returned "File not found: 15Twto21spGLwiby7_yGO_xquFXtfJIAo". Details: "File not found: 15Twto21spGLwiby7_yGO_xquFXtfJIAo">

**Comment by gwang-kim** [comment]
Thank you for finding the issue! I fixed it.
