### ISSUE TITLE
Error trying to train

### ISSUE THREAD

**Issue by corranmac** [gwang-kim/DiffusionCLIP#3]
Hi there, Im trying to finetune your FFHQ model but get this error:

Loading ResNet ArcFace
Prepare identity latent
precomputed/CelebA_HQ_train_t500_nim100_ninv40_pairs.pth
ERROR - main.py - 2022-04-05 01:37:56,717 - Traceback (most recent call last):
  File "main.py", line 211, in main
    runner.clip_finetune()
  File "/content/DiffusionCLIP/diffusionclip.py", line 143, in clip_finetune
    train_dataset, test_dataset = get_dataset(self.config.data.dataset, DATASET_PATHS, self.config)
  File "/content/DiffusionCLIP/datasets/data_utils.py", line 13, in get_dataset
    train_dataset, test_dataset = get_celeba_dataset(dataset_paths['CelebA_HQ'], config)
  File "/content/DiffusionCLIP/datasets/CelebA_HQ_dataset.py", line 55, in get_celeba_dataset
    train_transform, config.data.image_size)
  File "/content/DiffusionCLIP/datasets/CelebA_HQ_dataset.py", line 16, in __init__
    meminit=False,
lmdb.Error: /data/DiffusionCLIP/celeba_hq/LMDB_train: No such file or directory

**Comment by gwang-kim** [comment]
Thanks for your interest in our work, @corranmac. CelebA-HQ and AFHQ-Dog datasets are required to be preprocessed in LMDB format.  I updated the codes for this and the instructions in the Dataset section of README. 
```
# CelebA-HQ 256x256
bash data_download.sh celeba_hq .
```

**Comment by Hayeon-kimm** [comment]
I downloaded it. However, I can't see data.mdb. I can only see the raw_images folder. How can get it?
