### ISSUE TITLE
Is there any way to finetune in colab?

### ISSUE THREAD

**Issue by loboere** [gwang-kim/DiffusionCLIP#4]
Is there any way to finetune in colab?, maybe reducing batch size or something similar

**Comment by gwang-kim** [comment]
Thanks for your interest in our work, @loboere. Unfortunately, for now, VRAM of 12 GB+ for 256x256 images is required at a minimum and Colab allows 11GB VRAM. I think I can reduce the GPU memory by optimizing the code and if I finish it, I will inform you.
