### ISSUE TITLE
我有个问题，希望大佬回答

### ISSUE THREAD

**Issue by zhou431496** [gwang-kim/DiffusionCLIP#5]
如果在训练的时候我将n_train_step改为2，并且多训练是否可以得到可以接受的结果 。我12g的显存无法跑n_train_step=6的代码

**Comment by gwang-kim** [comment]
Thanks for your interest in our work, @loboere. It depends on the types of attributes. Emprically, I found that n_train_step=3 works well for some attributes. Also, I think I can reduce the GPU memory under 11GB by optimizing the code. If I finish it, I will inform you.

**Comment by zhou431496** [comment]
感谢您的回复，如果我将该工作引入到图像修复，是否可行呢。期待您的回复

**Comment by gwang-kim** [comment]
Yes, I think the ideas of DiffusionCLIP can be also applied to the reconstruction works.
