### ISSUE TITLE
CLIP文本引导的特征对一个正面的人脸是否有效呢

### ISSUE THREAD

**Issue by zhou431496** [gwang-kim/DiffusionCLIP#6]
大佬你好，如果我们使用扩散模型和CLIP进行人脸正面化操作，是否可行呢。我并不知道CLIP对”a frontal face“有效。希望大佬能给我们一点建议。期待您的回复

**Comment by gwang-kim** [comment]
I'm sorry to say that I can not give you great advice as I have no experience with face fractalization.
