### ISSUE TITLE
How to see the reconstructed face ? 

### ISSUE THREAD

**Issue by Jiakui** [gwang-kim/DiffusionCLIP#9]
Dear author,

The command  "python main.py --edit_one_image  "  let me see the edited face, but I also want to see the reconstructed face without any editing. How could I do that ?

Thanks!

**Comment by winnechan** [comment]
I think you can try setting "self.args.deterministic_inv" as True. However, in my reimplementation of the "edit_one_image" function for my own diffusion model, I cannot reconstruct the image for large t0.

**Comment by gwang-kim** [comment]
Hi, @Jiakui. 
As @winnechan commented, you can try setting `self.args.deterministic_inv` as 1.
